name: levy_notification
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  levy_core:
    path: ../levy_core
  #    git:
  #      url: https://github.com/andreleitejr/levy_core.git

  levy_dependencies:
    path: ../levy_dependencies

  levy_shared_entities:
    path: ../levy_shared_entities

  levy_theme:
    path: ../levy_theme

  levy_test_utils:
    path: ../levy_test_utils
  #    git:
  #      url: https://github.com/andreleitejr/levy_test_utils.git

  auto_route:
  auto_route_generator:
  flutter_riverpod:
  get_it:
  injectable:
  intl:
  json_annotation:
  shimmer:
  slang:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  golden_toolkit: ^0.15.0